### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by mrecht** [quintanar401/autocomplete-kdb-q#6]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Ubuntu 16.10
**Thrown From**: [autocomplete-kdb-q](https://github.com/quintanar401/autocomplete-kdb-q) package 0.5.7

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /home/marc/.atom/packages/autocomplete-kdb-q/lib/parser.coffee:132

TypeError: Cannot read property 'length' of undefined
    at Parser.module.exports.Parser.parseLine (/packages/autocomplete-kdb-q/lib/parser.coffee:132:26)
    at Parser.module.exports.Parser.parseFile (/packages/autocomplete-kdb-q/lib/parser.coffee:116:20)
    at /packages/autocomplete-kdb-q/lib/parser.coffee:38:18
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at TokenBuffer.module.exports.TokenBuffer.updateNextChunk (/packages/autocomplete-kdb-q/lib/tokenBuffer.coffee:62:16)
    at /packages/autocomplete-kdb-q/lib/tokenBuffer.coffee:76:17
    at /packages/autocomplete-kdb-q/node_modules/underscore/underscore.js:666:47
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.29.17 
autocomplete-kdb-q 0.5.7 
autocomplete-python 1.8.62 
busy-signal 1.3.0 
connect-kdb-q 0.4.6 
go-debug 1.2.0 
go-plus 5.3.4 
go-signature-statusbar 1.2.0 
hyperclick 0.0.40 
ink 0.6.5 
intentions 1.1.2 
julia-client 0.5.12 
language-groovy 0.6.0 
language-julia 0.11.0 
language-kdb-q 0.3.1 
latex-completions 0.3.2 
linter 2.1.2 
linter-ui-default 1.2.1 
script 3.14.1 
tool-bar 1.1.0 
uber-juno 0.1.1 
```

**Comment by quintanar401** [comment]
Could you provide a code sample - some context and when you type something this exception happens? There was a similar issue with long comments but it is fixed now.

**Comment by mrecht** [comment]
Sorry, I am unable to reproduce it...
